/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopauto;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author RUSHABH
 */
public class stock extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form stock
     */
    Container container = getContentPane();
    JButton add = new JButton("ADDSTOCK");
    JButton upd = new JButton("UPDATESTOCK");
    JButton del = new JButton("DELETESTOCK");
    JLabel r=new JLabel("STOCK DETAILS");
   
    public stock() {
        initComponents();
        setLayoutManager();
        setLocationAndSize();
        addComponentsToContainer();
        addActionEvent();

    }
        public void setLayoutManager() {
        container.setLayout(null);
    }

    public void setLocationAndSize() {
        add.setBounds(20, 100, 100, 30);
        upd.setBounds(20, 150, 100, 30);
        del.setBounds(20, 200, 100, 30);
        r.setBounds(150,0,100,30);
   //     table.setBounds(50,250,1000,300);
    }

    public void addComponentsToContainer() {
        container.add(add);
        container.add(upd);
        container.add(del);
        container.add(r);
     //   container.add(table);
    }
    public void addActionEvent() {
        add.addActionListener(this);
        upd.addActionListener(this);
        del.addActionListener(this);
    }
    public void showdata() throws ClassNotFoundException, SQLException{
        try{ 
        Class.forName("com.mysql.jdbc.Driver");  // (1)
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shopauto", "root", "root"); // (2)
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from register");
            Vector v1 = new Vector();
            Vector v2 = new Vector();
            
            while (rs.next()) {
             String ids = rs.getString(1);
             String name = rs.getString(2);
                v1.add(ids);
                v2.add(name);
            }
            JComboBox c1 = new JComboBox(v1);
            c1.setBounds(150, 110, 150, 20);
            JComboBox c2 = new JComboBox(v2);
            c2.setBounds(150, 180, 150, 20);

            container.add(c1);
            container.add(c2);
            st.close();
            rs.close();
        }
        catch(Exception e)
        {
            
        }
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==add)
        {
            try {
                showdata();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(stock.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(stock.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        stock frame = new stock();//args[0]);
        frame.setTitle("STOCK");
        frame.setVisible(true);
        //frame.setSize(1000,1000);
        frame.setBounds(20, 20, 370, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(true);

        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new stock().setVisible(true);
//            }
//        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
